### ISSUE TITLE
SBT doesn't resolve this

### ISSUE THREAD

**Issue by Andycharalambous** [conduktor/azure-kafka-oauthbearer#6]
Hi,

I don't see that this is published in mavenrepository - can you please provide information on the resolver setup in SBT to use?

Thanks

**Comment by qboileau** [comment]
This project is not published on maven central but on github directly, you need to add Conduktor Github maven registry in resolver list like 
in SBT
```sbt
resolvers += s"GitHub Conduktor Apache Maven Packages" at s"https://maven.pkg.github.com/conduktor/_/"
``` 
in maven 
```xml
    <repositories>
        <repository>
            <id>github</id>
            <name>GitHub Conduktor Apache Maven Packages</name>
            <url>https://maven.pkg.github.com/conduktor/_/</url>
        </repository>
    </repositories>
```

Will add them to the README, thanks for noticing this.
